# Generated by Django 5.2.7 on 2025-11-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('height', models.FloatField(help_text='Height in meters')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('types', models.CharField(help_text='Comma-separated types', max_length=200)),
                ('family', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Pokemon',
                'ordering': ['pokemon_id', 'name'],
            },
        ),
    ]
